# Generated by Django 6.0 on 2026-01-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingplan',
            old_name='duration_days',
            new_name='duration_weeks',
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner Track'), ('intermediate', 'Intermediate Track'), ('advanced', 'Advanced Track')], max_length=20),
        ),
    ]
