# Generated by Django 6.0 on 2026-01-07 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_course_is_active_pricingplan_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner Track'), ('intermediate', 'Intermediate Track'), ('advanced', 'Advanced Track')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.TextField(blank=True, help_text='One feature per line', null=True)),
                ('description', models.TextField()),
                ('duration_weeks', models.PositiveIntegerField(default=90, help_text='Duration in weeks (e.g. 30, 90, 180)')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academy.plan'),
        ),
        migrations.AlterField(
            model_name='planenrollment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.plan'),
        ),
        migrations.DeleteModel(
            name='PricingPlan',
        ),
    ]
