# Generated by Django 6.0 on 2026-01-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_plan_alter_course_plan_alter_planenrollment_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planenrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
