# Generated by Django 6.0 on 2026-01-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('cta_text', models.CharField(default='Enroll Now →', max_length=50)),
                ('cta_url', models.CharField(default='/pricing/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
