# Generated by Django 6.0 on 2026-01-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_programoutcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='programoutcome',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap icon class (e.g. bi-shield-lock)', max_length=50),
        ),
        migrations.AddField(
            model_name='programoutcome',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
    ]
