# Generated by Django 6.0 on 2026-01-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_programoutcome_icon_programoutcome_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programoutcome',
            name='icon',
        ),
        migrations.AddField(
            model_name='programoutcome',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload PNG / SVG icon (recommended: transparent background)', upload_to='program_icons/'),
        ),
    ]
