# Generated by Django 6.0 on 2026-01-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_remove_programoutcome_icon_programoutcome_icon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_deadline', models.DateTimeField()),
                ('max_slots', models.PositiveIntegerField(default=50)),
                ('slots_taken', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-registration_deadline'],
            },
        ),
    ]
